spring.application.name=spain
token.AEMET=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxdnVlbHZvODJAZ21haWwuY29tIiwianRpIjoiZmRlNzI5NmEtYTc3YS00YzU0LTkyODAtYzdiYTQ3MjNlYjExIiwiZXhwIjoxNzk5NjQ3NzM4LCJpc3MiOiJBRU1FVCIsImlhdCI6MTc5MTAwNzczOCwidXNlcklkIjoiZmRlNzI5NmEtYTc3YS00YzU0LTkyODAtYzdiYTQ3MjNlYjExIiwicm9sZSI6IiJ9.8eCnpYOSrsp6PVuX7owf7ZKZs6RJHEEHTJ9rORZsqlg
